#pragma once

#include "antlr4-runtime.h"
#include "JakShellParser.h"

/**
 * This class defines an abstract visitor for a parse tree
 * generated by ShellParser.
 */
class ShellBaseVisitor : public antlr4::tree::AbstractParseTreeVisitor {
public:

  /**
   * Visit parse trees produced by ShellParser.
   */

  virtual antlrcpp::Any visitCommand(JakShellParser::CommandContext *context) = 0;

  virtual antlrcpp::Any visitListFiles(JakShellParser::ListFilesContext *context) = 0;

  virtual antlrcpp::Any visitChangeDirectory(JakShellParser::ChangeDirectoryContext *context) = 0;

  virtual antlrcpp::Any visitMakeDirectory(JakShellParser::MakeDirectoryContext *context) = 0;

  virtual antlrcpp::Any visitRemoveFile(JakShellParser::RemoveFileContext *context) = 0;

  virtual antlrcpp::Any visitEchoText(JakShellParser::EchoTextContext *context) = 0;

  virtual antlrcpp::Any visitExecuteCommand(JakShellParser::ExecuteCommandContext *context) = 0;

  virtual antlrcpp::Any visitCreateFile(JakShellParser::CreateFileContext *context) = 0;

  virtual antlrcpp::Any visitShowDate(JakShellParser::ShowDateContext *context) = 0;

  virtual antlrcpp::Any visitShowTime(JakShellParser::ShowTimeContext *context) = 0;

  virtual antlrcpp::Any visitCopyFile(JakShellParser::CopyFileContext *context) = 0;

  virtual antlrcpp::Any visitMoveFile(JakShellParser::MoveFileContext *context) = 0;

};
